#ifndef _FDA_COEFF_1000_10_100_H_
#define _FDA_COEFF_1000_10_100_H_


/*



* Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.14 and the Signal Processing Toolbox 6.17.
 *
 * Generated on: 02-May-2013 12:58:24
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 14
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2012a/extern/include/tmwtypes.h 
 */
#define FILTER_TAP_SIZE 14
const double filter_coeffs[FILTER_TAP_SIZE] = {
   0.005271208909706,  0.05204636786996,  0.05315761628452,  0.07562063364867,
    0.09406855250555,    0.108343855546,   0.1160610649931,   0.1160610649931,
      0.108343855546,  0.09406855250555,  0.07562063364867,  0.05315761628452,
    0.05204636786996, 0.005271208909706
};


#endif
