#ifndef _FDACOEFS_30HZ_10HZ_CUTOFF_H_
#define _FDACOEFS_30HZ_10HZ_CUTOFF_H_


/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.14 and the Signal Processing Toolbox 6.17.
 *
 * Generated on: 21-Apr-2013 22:30:38
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : No
 */

/* 
 * Expected path to tmwtypes.h 
 * /home/dehann/mit/software/matlab/local/extern/include/tmwtypes.h 
 */
#define FILTER_TAP_SIZE 11


const double filter_coeffs[FILTER_TAP_SIZE] = {
     0.1002473737389,   0.3347967894847,   0.4680244782963,    0.264342767525,
   -0.06959419617062,  -0.1510172005126,-0.004928732194041,  0.06970601074556,
    0.01435355137271, -0.02566570414098,-0.008867086363492
};


#endif