#ifndef KF_TUNING_PARAMETERS_HPP_
#define KF_TUNING_PARAMETERS_HPP_


#define PROCESS_NOISE_JOINT_POSITIONS   0.005;
#define PROCESS_NOISE_JOINT_VELOCITIES  0.005;

#endif /*KF_TUNING_PARAMETERS_HPP_*/
