#!/usr/bin/python

import sys
import gzip

gzfile = gzip.open (sys.argv[1], "rb")

count = 0

while True:
    firstline = gzfile.readline ()
    width, height = [ int (i) for i in firstline.split ()[1:3]]
    data = gzfile.read (width * height * 3)

    fname = "output-%06d.ppm" % count
    outf = file (fname, "wb")
    outf.write (firstline)
    outf.write (data)
    outf.close ()
    count += 1
    print fname
