#!/bin/bash

if (( $# < 2 ))
then
    echo "usage: `basename $0` <framerate> <input_file.ppms.gz>"
    exit 1
fi

framerate=$1
shift 1

# convert a .ppms.gz file (produced by viewer) into an avi with the ffv1 lossless codec
# for "web" quality, use -b 2M
zcat $* | ffmpeg -r $framerate -y -vcodec ppm -f image2pipe -i - -vcodec ffv1 output.avi 

