#!/bin/bash

if (( $# < 3 ))
then
    echo "usage: `basename $0` <qscale> <framerate> <input_file.ppms.gz>"
    exit 1
fi

framerate=$2
#bitrate=$1
qscale=$1
fname=`basename $3 .ppms.gz`
shift 2

# convert a .ppms.gz file (produced by viewer) into an mpeg4 file, using high quality.
# for "web" quality, use -b 2M
zcat $* | ffmpeg -qscale $qscale -r $framerate -y -vcodec ppm -f image2pipe -i - -vcodec msmpeg4v2 $fname.avi 
