all:
	echo Making MITs ROS DRC repo
	make -C atlas_gazebo_msgs
	make -C translators
	make -C mit_drcsim_plugins
	make -C keyboard_teleop
	make -C keyboard_driving
	make -C multisense_command
	echo "===Finished making MIT's ROS DRC repo===";

