/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class absolute_tf_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public String robot_name;
    public int num_links;
    public drc.link_transform_t tf[];
 
    public absolute_tf_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xd091eca44b141283L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.absolute_tf_t.class))
            return 0L;
 
        classes.add(drc.absolute_tf_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + drc.link_transform_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        __strbuf = new char[this.robot_name.length()]; this.robot_name.getChars(0, this.robot_name.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeInt(this.num_links); 
 
        for (int a = 0; a < this.num_links; a++) {
            this.tf[a]._encodeRecursive(outs); 
        }
 
    }
 
    public absolute_tf_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public absolute_tf_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.absolute_tf_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.absolute_tf_t o = new drc.absolute_tf_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.robot_name = new String(__strbuf);
 
        this.num_links = ins.readInt();
 
        this.tf = new drc.link_transform_t[(int) num_links];
        for (int a = 0; a < this.num_links; a++) {
            this.tf[a] = drc.link_transform_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public drc.absolute_tf_t copy()
    {
        drc.absolute_tf_t outobj = new drc.absolute_tf_t();
        outobj.utime = this.utime;
 
        outobj.robot_name = this.robot_name;
 
        outobj.num_links = this.num_links;
 
        outobj.tf = new drc.link_transform_t[(int) num_links];
        for (int a = 0; a < this.num_links; a++) {
            outobj.tf[a] = this.tf[a].copy();
        }
 
        return outobj;
    }
 
}

