/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class atlas_raw_imu_batch_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int num_packets;
    public drc.atlas_raw_imu_t raw_imu[];
 
    public atlas_raw_imu_batch_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xe24b510bcb63f295L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.atlas_raw_imu_batch_t.class))
            return 0L;
 
        classes.add(drc.atlas_raw_imu_batch_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + drc.atlas_raw_imu_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.num_packets); 
 
        for (int a = 0; a < this.num_packets; a++) {
            this.raw_imu[a]._encodeRecursive(outs); 
        }
 
    }
 
    public atlas_raw_imu_batch_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public atlas_raw_imu_batch_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.atlas_raw_imu_batch_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.atlas_raw_imu_batch_t o = new drc.atlas_raw_imu_batch_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.num_packets = ins.readInt();
 
        this.raw_imu = new drc.atlas_raw_imu_t[(int) num_packets];
        for (int a = 0; a < this.num_packets; a++) {
            this.raw_imu[a] = drc.atlas_raw_imu_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public drc.atlas_raw_imu_batch_t copy()
    {
        drc.atlas_raw_imu_batch_t outobj = new drc.atlas_raw_imu_batch_t();
        outobj.utime = this.utime;
 
        outobj.num_packets = this.num_packets;
 
        outobj.raw_imu = new drc.atlas_raw_imu_t[(int) num_packets];
        for (int a = 0; a < this.num_packets; a++) {
            outobj.raw_imu[a] = this.raw_imu[a].copy();
        }
 
        return outobj;
    }
 
}

