/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class atlas_raw_imu_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public long packet_count;
    public double delta_rotation[];
    public double linear_acceleration[];
 
    public atlas_raw_imu_t()
    {
        delta_rotation = new double[3];
        linear_acceleration = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x90eec8e5d8bdd893L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.atlas_raw_imu_t.class))
            return 0L;
 
        classes.add(drc.atlas_raw_imu_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeLong(this.packet_count); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.delta_rotation[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.linear_acceleration[a]); 
        }
 
    }
 
    public atlas_raw_imu_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public atlas_raw_imu_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.atlas_raw_imu_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.atlas_raw_imu_t o = new drc.atlas_raw_imu_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.packet_count = ins.readLong();
 
        this.delta_rotation = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.delta_rotation[a] = ins.readDouble();
        }
 
        this.linear_acceleration = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.linear_acceleration[a] = ins.readDouble();
        }
 
    }
 
    public drc.atlas_raw_imu_t copy()
    {
        drc.atlas_raw_imu_t outobj = new drc.atlas_raw_imu_t();
        outobj.utime = this.utime;
 
        outobj.packet_count = this.packet_count;
 
        outobj.delta_rotation = new double[(int) 3];
        System.arraycopy(this.delta_rotation, 0, outobj.delta_rotation, 0, 3); 
        outobj.linear_acceleration = new double[(int) 3];
        System.arraycopy(this.linear_acceleration, 0, outobj.linear_acceleration, 0, 3); 
        return outobj;
    }
 
}

