/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class controller_mode_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public byte mode;
 
    public controller_mode_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x00b83f18f8ba4717L;
 
    public static final byte BDI = (byte) 0;
    public static final byte MIT = (byte) 1;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.controller_mode_t.class))
            return 0L;
 
        classes.add(drc.controller_mode_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeByte(this.mode); 
 
    }
 
    public controller_mode_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public controller_mode_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.controller_mode_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.controller_mode_t o = new drc.controller_mode_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.mode = ins.readByte();
 
    }
 
    public drc.controller_mode_t copy()
    {
        drc.controller_mode_t outobj = new drc.controller_mode_t();
        outobj.utime = this.utime;
 
        outobj.mode = this.mode;
 
        return outobj;
    }
 
}

