/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class contact_state_stamped_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public String robot_name;
    public int num_contacts;
    public String id[];
    public boolean inContact[];
    public drc.vector_3d_t contactForce[];
 
    public contact_state_stamped_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x817e83c7c53ce45cL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.contact_state_stamped_t.class))
            return 0L;
 
        classes.add(drc.contact_state_stamped_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + drc.vector_3d_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        __strbuf = new char[this.robot_name.length()]; this.robot_name.getChars(0, this.robot_name.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeInt(this.num_contacts); 
 
        for (int a = 0; a < this.num_contacts; a++) {
            __strbuf = new char[this.id[a].length()]; this.id[a].getChars(0, this.id[a].length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
        }
 
        for (int a = 0; a < this.num_contacts; a++) {
            outs.writeByte( this.inContact[a] ? 1 : 0); 
        }
 
        for (int a = 0; a < this.num_contacts; a++) {
            this.contactForce[a]._encodeRecursive(outs); 
        }
 
    }
 
    public contact_state_stamped_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public contact_state_stamped_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.contact_state_stamped_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.contact_state_stamped_t o = new drc.contact_state_stamped_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.robot_name = new String(__strbuf);
 
        this.num_contacts = ins.readInt();
 
        this.id = new String[(int) num_contacts];
        for (int a = 0; a < this.num_contacts; a++) {
            __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.id[a] = new String(__strbuf);
        }
 
        this.inContact = new boolean[(int) num_contacts];
        for (int a = 0; a < this.num_contacts; a++) {
            this.inContact[a] = ins.readByte()!=0;
        }
 
        this.contactForce = new drc.vector_3d_t[(int) num_contacts];
        for (int a = 0; a < this.num_contacts; a++) {
            this.contactForce[a] = drc.vector_3d_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public drc.contact_state_stamped_t copy()
    {
        drc.contact_state_stamped_t outobj = new drc.contact_state_stamped_t();
        outobj.utime = this.utime;
 
        outobj.robot_name = this.robot_name;
 
        outobj.num_contacts = this.num_contacts;
 
        outobj.id = new String[(int) num_contacts];
        if (this.num_contacts > 0)
            System.arraycopy(this.id, 0, outobj.id, 0, this.num_contacts); 
        outobj.inContact = new boolean[(int) num_contacts];
        if (this.num_contacts > 0)
            System.arraycopy(this.inContact, 0, outobj.inContact, 0, this.num_contacts); 
        outobj.contactForce = new drc.vector_3d_t[(int) num_contacts];
        for (int a = 0; a < this.num_contacts; a++) {
            outobj.contactForce[a] = this.contactForce[a].copy();
        }
 
        return outobj;
    }
 
}

