/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class controller_status_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public byte state;
    public long controller_utime;
    public float V;
    public float Vdot;
 
    public controller_status_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xc9507d072c15ad5eL;
 
    public static final byte UNKNOWN = (byte) 0;
    public static final byte STANDING = (byte) 1;
    public static final byte WALKING = (byte) 2;
    public static final byte HARNESSED = (byte) 3;
    public static final byte QUASISTATIC = (byte) 4;
    public static final byte BRACING = (byte) 5;
    public static final byte CRAWLING = (byte) 6;
    public static final byte DUMMY = (byte) 7;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.controller_status_t.class))
            return 0L;
 
        classes.add(drc.controller_status_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeByte(this.state); 
 
        outs.writeLong(this.controller_utime); 
 
        outs.writeFloat(this.V); 
 
        outs.writeFloat(this.Vdot); 
 
    }
 
    public controller_status_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public controller_status_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.controller_status_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.controller_status_t o = new drc.controller_status_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.state = ins.readByte();
 
        this.controller_utime = ins.readLong();
 
        this.V = ins.readFloat();
 
        this.Vdot = ins.readFloat();
 
    }
 
    public drc.controller_status_t copy()
    {
        drc.controller_status_t outobj = new drc.controller_status_t();
        outobj.utime = this.utime;
 
        outobj.state = this.state;
 
        outobj.controller_utime = this.controller_utime;
 
        outobj.V = this.V;
 
        outobj.Vdot = this.Vdot;
 
        return outobj;
    }
 
}

