/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class data_request_list_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public byte num_requests;
    public drc.data_request_t requests[];
 
    public data_request_list_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x7ab2710d5e84e81eL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.data_request_list_t.class))
            return 0L;
 
        classes.add(drc.data_request_list_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + drc.data_request_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeByte(this.num_requests); 
 
        for (int a = 0; a < this.num_requests; a++) {
            this.requests[a]._encodeRecursive(outs); 
        }
 
    }
 
    public data_request_list_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public data_request_list_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.data_request_list_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.data_request_list_t o = new drc.data_request_list_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.num_requests = ins.readByte();
 
        this.requests = new drc.data_request_t[(int) num_requests];
        for (int a = 0; a < this.num_requests; a++) {
            this.requests[a] = drc.data_request_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public drc.data_request_list_t copy()
    {
        drc.data_request_list_t outobj = new drc.data_request_list_t();
        outobj.utime = this.utime;
 
        outobj.num_requests = this.num_requests;
 
        outobj.requests = new drc.data_request_t[(int) num_requests];
        for (int a = 0; a < this.num_requests; a++) {
            outobj.requests[a] = this.requests[a].copy();
        }
 
        return outobj;
    }
 
}

