/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class driving_control_cmd_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public byte type;
    public double steering_angle;
    public double throttle_value;
    public double brake_value;
 
    public driving_control_cmd_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x4c740f35351b7e29L;
 
    public static final byte TYPE_START_CAR = (byte) 0;
    public static final byte TYPE_GEAR_FORWARD = (byte) 1;
    public static final byte TYPE_GEAR_NEUTRAL = (byte) 2;
    public static final byte TYPE_GEAR_REVERSE = (byte) 3;
    public static final byte TYPE_DRIVE = (byte) 4;
    public static final byte TYPE_BRAKE = (byte) 5;
    public static final byte TYPE_E_STOP = (byte) 6;
    public static final byte TYPE_SWITCH_OFF_ENGINE = (byte) 7;
    public static final byte TYPE_DRIVE_DELTA_STEERING = (byte) 8;
    public static final byte TYPE_DRIVE_DELTA_THROTTLE = (byte) 9;
    public static final byte TYPE_HANDBRAKE_ON = (byte) 10;
    public static final byte TYPE_HANDBRAKE_OFF = (byte) 11;
    public static final byte TYPE_START_SEQUENCE = (byte) 12;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.driving_control_cmd_t.class))
            return 0L;
 
        classes.add(drc.driving_control_cmd_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeByte(this.type); 
 
        outs.writeDouble(this.steering_angle); 
 
        outs.writeDouble(this.throttle_value); 
 
        outs.writeDouble(this.brake_value); 
 
    }
 
    public driving_control_cmd_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public driving_control_cmd_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.driving_control_cmd_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.driving_control_cmd_t o = new drc.driving_control_cmd_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.type = ins.readByte();
 
        this.steering_angle = ins.readDouble();
 
        this.throttle_value = ins.readDouble();
 
        this.brake_value = ins.readDouble();
 
    }
 
    public drc.driving_control_cmd_t copy()
    {
        drc.driving_control_cmd_t outobj = new drc.driving_control_cmd_t();
        outobj.utime = this.utime;
 
        outobj.type = this.type;
 
        outobj.steering_angle = this.steering_angle;
 
        outobj.throttle_value = this.throttle_value;
 
        outobj.brake_value = this.brake_value;
 
        return outobj;
    }
 
}

