/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class estimated_biases_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public float x;
    public float y;
    public float z;
    public byte mode;
 
    public estimated_biases_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x80fe9a527c13dec1L;
 
    public static final byte ESTIMATING = (byte) 0;
    public static final byte LOCKED = (byte) 1;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.estimated_biases_t.class))
            return 0L;
 
        classes.add(drc.estimated_biases_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeFloat(this.x); 
 
        outs.writeFloat(this.y); 
 
        outs.writeFloat(this.z); 
 
        outs.writeByte(this.mode); 
 
    }
 
    public estimated_biases_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public estimated_biases_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.estimated_biases_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.estimated_biases_t o = new drc.estimated_biases_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.x = ins.readFloat();
 
        this.y = ins.readFloat();
 
        this.z = ins.readFloat();
 
        this.mode = ins.readByte();
 
    }
 
    public drc.estimated_biases_t copy()
    {
        drc.estimated_biases_t outobj = new drc.estimated_biases_t();
        outobj.utime = this.utime;
 
        outobj.x = this.x;
 
        outobj.y = this.y;
 
        outobj.z = this.z;
 
        outobj.mode = this.mode;
 
        return outobj;
    }
 
}

