/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class footstep_goal_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public String robot_name;
    public drc.position_3d_t pos;
    public double step_speed;
    public double step_height;
    public int id;
    public boolean is_right_foot;
    public boolean is_in_contact;
    public boolean fixed_x;
    public boolean fixed_y;
    public boolean fixed_z;
    public boolean fixed_roll;
    public boolean fixed_pitch;
    public boolean fixed_yaw;
 
    public footstep_goal_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x610b41d9bd2c8155L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.footstep_goal_t.class))
            return 0L;
 
        classes.add(drc.footstep_goal_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + drc.position_3d_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        __strbuf = new char[this.robot_name.length()]; this.robot_name.getChars(0, this.robot_name.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        this.pos._encodeRecursive(outs); 
 
        outs.writeDouble(this.step_speed); 
 
        outs.writeDouble(this.step_height); 
 
        outs.writeInt(this.id); 
 
        outs.writeByte( this.is_right_foot ? 1 : 0); 
 
        outs.writeByte( this.is_in_contact ? 1 : 0); 
 
        outs.writeByte( this.fixed_x ? 1 : 0); 
 
        outs.writeByte( this.fixed_y ? 1 : 0); 
 
        outs.writeByte( this.fixed_z ? 1 : 0); 
 
        outs.writeByte( this.fixed_roll ? 1 : 0); 
 
        outs.writeByte( this.fixed_pitch ? 1 : 0); 
 
        outs.writeByte( this.fixed_yaw ? 1 : 0); 
 
    }
 
    public footstep_goal_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public footstep_goal_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.footstep_goal_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.footstep_goal_t o = new drc.footstep_goal_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.robot_name = new String(__strbuf);
 
        this.pos = drc.position_3d_t._decodeRecursiveFactory(ins);
 
        this.step_speed = ins.readDouble();
 
        this.step_height = ins.readDouble();
 
        this.id = ins.readInt();
 
        this.is_right_foot = ins.readByte()!=0;
 
        this.is_in_contact = ins.readByte()!=0;
 
        this.fixed_x = ins.readByte()!=0;
 
        this.fixed_y = ins.readByte()!=0;
 
        this.fixed_z = ins.readByte()!=0;
 
        this.fixed_roll = ins.readByte()!=0;
 
        this.fixed_pitch = ins.readByte()!=0;
 
        this.fixed_yaw = ins.readByte()!=0;
 
    }
 
    public drc.footstep_goal_t copy()
    {
        drc.footstep_goal_t outobj = new drc.footstep_goal_t();
        outobj.utime = this.utime;
 
        outobj.robot_name = this.robot_name;
 
        outobj.pos = this.pos.copy();
 
        outobj.step_speed = this.step_speed;
 
        outobj.step_height = this.step_height;
 
        outobj.id = this.id;
 
        outobj.is_right_foot = this.is_right_foot;
 
        outobj.is_in_contact = this.is_in_contact;
 
        outobj.fixed_x = this.fixed_x;
 
        outobj.fixed_y = this.fixed_y;
 
        outobj.fixed_z = this.fixed_z;
 
        outobj.fixed_roll = this.fixed_roll;
 
        outobj.fixed_pitch = this.fixed_pitch;
 
        outobj.fixed_yaw = this.fixed_yaw;
 
        return outobj;
    }
 
}

