/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class gaze_command_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int affordance_id;
 
    public gaze_command_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xfb47748f7dc61026L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.gaze_command_t.class))
            return 0L;
 
        classes.add(drc.gaze_command_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.affordance_id); 
 
    }
 
    public gaze_command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public gaze_command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.gaze_command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.gaze_command_t o = new drc.gaze_command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.affordance_id = ins.readInt();
 
    }
 
    public drc.gaze_command_t copy()
    {
        drc.gaze_command_t outobj = new drc.gaze_command_t();
        outobj.utime = this.utime;
 
        outobj.affordance_id = this.affordance_id;
 
        return outobj;
    }
 
}

