/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class grasp_transition_state_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int affordance_uid;
    public drc.position_3d_t hand_pose;
    public boolean grasp_on;
    public short grasp_type;
    public boolean power_grasp;
    public int num_joints;
    public String joint_name[];
    public double joint_position[];
 
    public grasp_transition_state_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x1b288dd50aa79ac7L;
 
    public static final short LEFT = (short) 0;
    public static final short RIGHT = (short) 1;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.grasp_transition_state_t.class))
            return 0L;
 
        classes.add(drc.grasp_transition_state_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + drc.position_3d_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.affordance_uid); 
 
        this.hand_pose._encodeRecursive(outs); 
 
        outs.writeByte( this.grasp_on ? 1 : 0); 
 
        outs.writeShort(this.grasp_type); 
 
        outs.writeByte( this.power_grasp ? 1 : 0); 
 
        outs.writeInt(this.num_joints); 
 
        for (int a = 0; a < this.num_joints; a++) {
            __strbuf = new char[this.joint_name[a].length()]; this.joint_name[a].getChars(0, this.joint_name[a].length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
        }
 
        for (int a = 0; a < this.num_joints; a++) {
            outs.writeDouble(this.joint_position[a]); 
        }
 
    }
 
    public grasp_transition_state_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public grasp_transition_state_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.grasp_transition_state_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.grasp_transition_state_t o = new drc.grasp_transition_state_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        this.affordance_uid = ins.readInt();
 
        this.hand_pose = drc.position_3d_t._decodeRecursiveFactory(ins);
 
        this.grasp_on = ins.readByte()!=0;
 
        this.grasp_type = ins.readShort();
 
        this.power_grasp = ins.readByte()!=0;
 
        this.num_joints = ins.readInt();
 
        this.joint_name = new String[(int) num_joints];
        for (int a = 0; a < this.num_joints; a++) {
            __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.joint_name[a] = new String(__strbuf);
        }
 
        this.joint_position = new double[(int) num_joints];
        for (int a = 0; a < this.num_joints; a++) {
            this.joint_position[a] = ins.readDouble();
        }
 
    }
 
    public drc.grasp_transition_state_t copy()
    {
        drc.grasp_transition_state_t outobj = new drc.grasp_transition_state_t();
        outobj.utime = this.utime;
 
        outobj.affordance_uid = this.affordance_uid;
 
        outobj.hand_pose = this.hand_pose.copy();
 
        outobj.grasp_on = this.grasp_on;
 
        outobj.grasp_type = this.grasp_type;
 
        outobj.power_grasp = this.power_grasp;
 
        outobj.num_joints = this.num_joints;
 
        outobj.joint_name = new String[(int) num_joints];
        if (this.num_joints > 0)
            System.arraycopy(this.joint_name, 0, outobj.joint_name, 0, this.num_joints); 
        outobj.joint_position = new double[(int) num_joints];
        if (this.num_joints > 0)
            System.arraycopy(this.joint_position, 0, outobj.joint_position, 0, this.num_joints); 
        return outobj;
    }
 
}

