/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class local_map_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public long id;
    public long state_id;
    public int size_bytes;
    public byte data[];
 
    public local_map_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x8967a51c6172752dL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.local_map_t.class))
            return 0L;
 
        classes.add(drc.local_map_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeLong(this.id); 
 
        outs.writeLong(this.state_id); 
 
        outs.writeInt(this.size_bytes); 
 
        if (this.size_bytes > 0)
            outs.write(this.data, 0, size_bytes);
 
    }
 
    public local_map_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public local_map_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.local_map_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.local_map_t o = new drc.local_map_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.id = ins.readLong();
 
        this.state_id = ins.readLong();
 
        this.size_bytes = ins.readInt();
 
        this.data = new byte[(int) size_bytes];
        ins.readFully(this.data, 0, size_bytes); 
    }
 
    public drc.local_map_t copy()
    {
        drc.local_map_t outobj = new drc.local_map_t();
        outobj.utime = this.utime;
 
        outobj.id = this.id;
 
        outobj.state_id = this.state_id;
 
        outobj.size_bytes = this.size_bytes;
 
        outobj.data = new byte[(int) size_bytes];
        if (this.size_bytes > 0)
            System.arraycopy(this.data, 0, outobj.data, 0, this.size_bytes); 
        return outobj;
    }
 
}

