/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class map_cloud_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public long map_id;
    public long view_id;
    public float transform[][];
    public drc.map_blob_t blob;
 
    public map_cloud_t()
    {
        transform = new float[4][4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x567772cc2143d585L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.map_cloud_t.class))
            return 0L;
 
        classes.add(drc.map_cloud_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + drc.map_blob_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeLong(this.map_id); 
 
        outs.writeLong(this.view_id); 
 
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 4; b++) {
                outs.writeFloat(this.transform[a][b]); 
            }
        }
 
        this.blob._encodeRecursive(outs); 
 
    }
 
    public map_cloud_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public map_cloud_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.map_cloud_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.map_cloud_t o = new drc.map_cloud_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.map_id = ins.readLong();
 
        this.view_id = ins.readLong();
 
        this.transform = new float[(int) 4][(int) 4];
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 4; b++) {
                this.transform[a][b] = ins.readFloat();
            }
        }
 
        this.blob = drc.map_blob_t._decodeRecursiveFactory(ins);
 
    }
 
    public drc.map_cloud_t copy()
    {
        drc.map_cloud_t outobj = new drc.map_cloud_t();
        outobj.utime = this.utime;
 
        outobj.map_id = this.map_id;
 
        outobj.view_id = this.view_id;
 
        outobj.transform = new float[(int) 4][(int) 4];
        for (int a = 0; a < 4; a++) {
            System.arraycopy(this.transform[a], 0, outobj.transform[a], 0, 4);        }
 
        outobj.blob = this.blob.copy();
 
        return outobj;
    }
 
}

