/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class map_catalog_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int num_maps;
    public drc.map_params_t maps[];
    public int num_views;
    public drc.map_request_t views[];
 
    public map_catalog_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x46d77dfe619bbbcaL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.map_catalog_t.class))
            return 0L;
 
        classes.add(drc.map_catalog_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + drc.map_params_t._hashRecursive(classes)
             + drc.map_request_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.num_maps); 
 
        for (int a = 0; a < this.num_maps; a++) {
            this.maps[a]._encodeRecursive(outs); 
        }
 
        outs.writeInt(this.num_views); 
 
        for (int a = 0; a < this.num_views; a++) {
            this.views[a]._encodeRecursive(outs); 
        }
 
    }
 
    public map_catalog_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public map_catalog_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.map_catalog_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.map_catalog_t o = new drc.map_catalog_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.num_maps = ins.readInt();
 
        this.maps = new drc.map_params_t[(int) num_maps];
        for (int a = 0; a < this.num_maps; a++) {
            this.maps[a] = drc.map_params_t._decodeRecursiveFactory(ins);
        }
 
        this.num_views = ins.readInt();
 
        this.views = new drc.map_request_t[(int) num_views];
        for (int a = 0; a < this.num_views; a++) {
            this.views[a] = drc.map_request_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public drc.map_catalog_t copy()
    {
        drc.map_catalog_t outobj = new drc.map_catalog_t();
        outobj.utime = this.utime;
 
        outobj.num_maps = this.num_maps;
 
        outobj.maps = new drc.map_params_t[(int) num_maps];
        for (int a = 0; a < this.num_maps; a++) {
            outobj.maps[a] = this.maps[a].copy();
        }
 
        outobj.num_views = this.num_views;
 
        outobj.views = new drc.map_request_t[(int) num_views];
        for (int a = 0; a < this.num_views; a++) {
            outobj.views[a] = this.views[a].copy();
        }
 
        return outobj;
    }
 
}

