/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class message_ack_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public long message_id;
    public long message_utime;
 
    public message_ack_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xfa0777aff0ed5109L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.message_ack_t.class))
            return 0L;
 
        classes.add(drc.message_ack_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeLong(this.message_id); 
 
        outs.writeLong(this.message_utime); 
 
    }
 
    public message_ack_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public message_ack_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.message_ack_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.message_ack_t o = new drc.message_ack_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.message_id = ins.readLong();
 
        this.message_utime = ins.readLong();
 
    }
 
    public drc.message_ack_t copy()
    {
        drc.message_ack_t outobj = new drc.message_ack_t();
        outobj.utime = this.utime;
 
        outobj.message_id = this.message_id;
 
        outobj.message_utime = this.message_utime;
 
        return outobj;
    }
 
}

