/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class minimal_robot_state_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public drc.position_3d_t origin_position;
    public int num_joints;
    public float joint_position[];
 
    public minimal_robot_state_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x6f6e3e696510f0e9L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.minimal_robot_state_t.class))
            return 0L;
 
        classes.add(drc.minimal_robot_state_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + drc.position_3d_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        this.origin_position._encodeRecursive(outs); 
 
        outs.writeInt(this.num_joints); 
 
        for (int a = 0; a < this.num_joints; a++) {
            outs.writeFloat(this.joint_position[a]); 
        }
 
    }
 
    public minimal_robot_state_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public minimal_robot_state_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.minimal_robot_state_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.minimal_robot_state_t o = new drc.minimal_robot_state_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.origin_position = drc.position_3d_t._decodeRecursiveFactory(ins);
 
        this.num_joints = ins.readInt();
 
        this.joint_position = new float[(int) num_joints];
        for (int a = 0; a < this.num_joints; a++) {
            this.joint_position[a] = ins.readFloat();
        }
 
    }
 
    public drc.minimal_robot_state_t copy()
    {
        drc.minimal_robot_state_t outobj = new drc.minimal_robot_state_t();
        outobj.utime = this.utime;
 
        outobj.origin_position = this.origin_position.copy();
 
        outobj.num_joints = this.num_joints;
 
        outobj.joint_position = new float[(int) num_joints];
        if (this.num_joints > 0)
            System.arraycopy(this.joint_position, 0, outobj.joint_position, 0, this.num_joints); 
        return outobj;
    }
 
}

