/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class motionest_request_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public byte fusion_mode;
 
    public motionest_request_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x163c181378a1f58fL;
 
    public static final byte DEFAULT = (byte) 0;
    public static final byte VO = (byte) 1;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.motionest_request_t.class))
            return 0L;
 
        classes.add(drc.motionest_request_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeByte(this.fusion_mode); 
 
    }
 
    public motionest_request_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public motionest_request_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.motionest_request_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.motionest_request_t o = new drc.motionest_request_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.fusion_mode = ins.readByte();
 
    }
 
    public drc.motionest_request_t copy()
    {
        drc.motionest_request_t outobj = new drc.motionest_request_t();
        outobj.utime = this.utime;
 
        outobj.fusion_mode = this.fusion_mode;
 
        return outobj;
    }
 
}

