/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class plan_adjust_mode_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public short mode;
 
    public plan_adjust_mode_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xb83f18f1915c8b03L;
 
    public static final short RIGHT_HAND = (short) 0;
    public static final short LEFT_HAND = (short) 1;
    public static final short BOTH_HANDS = (short) 2;
    public static final short LEFT_FOOT = (short) 3;
    public static final short RIGHT_FOOT = (short) 4;
    public static final short BOTH_FEET = (short) 5;
    public static final short ALL = (short) 6;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.plan_adjust_mode_t.class))
            return 0L;
 
        classes.add(drc.plan_adjust_mode_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeShort(this.mode); 
 
    }
 
    public plan_adjust_mode_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public plan_adjust_mode_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.plan_adjust_mode_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.plan_adjust_mode_t o = new drc.plan_adjust_mode_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.mode = ins.readShort();
 
    }
 
    public drc.plan_adjust_mode_t copy()
    {
        drc.plan_adjust_mode_t outobj = new drc.plan_adjust_mode_t();
        outobj.utime = this.utime;
 
        outobj.mode = this.mode;
 
        return outobj;
    }
 
}

