/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class point_list_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public byte n_points;
    public short uv[][];
 
    public point_list_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x9eb092d6fcc311ddL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.point_list_t.class))
            return 0L;
 
        classes.add(drc.point_list_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeByte(this.n_points); 
 
        for (int a = 0; a < this.n_points; a++) {
            for (int b = 0; b < 2; b++) {
                outs.writeShort(this.uv[a][b]); 
            }
        }
 
    }
 
    public point_list_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public point_list_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.point_list_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.point_list_t o = new drc.point_list_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.n_points = ins.readByte();
 
        this.uv = new short[(int) n_points][(int) 2];
        for (int a = 0; a < this.n_points; a++) {
            for (int b = 0; b < 2; b++) {
                this.uv[a][b] = ins.readShort();
            }
        }
 
    }
 
    public drc.point_list_t copy()
    {
        drc.point_list_t outobj = new drc.point_list_t();
        outobj.utime = this.utime;
 
        outobj.n_points = this.n_points;
 
        outobj.uv = new short[(int) n_points][(int) 2];
        for (int a = 0; a < this.n_points; a++) {
            System.arraycopy(this.uv[a], 0, outobj.uv[a], 0, 2);        }
 
        return outobj;
    }
 
}

