/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class printf_reply_t implements lcm.lcm.LCMEncodable
{
    public int sheriff_id;
    public boolean robot;
    public byte n_printfs;
    public String printfs[];
 
    public printf_reply_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xcbad9167fec65004L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.printf_reply_t.class))
            return 0L;
 
        classes.add(drc.printf_reply_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeInt(this.sheriff_id); 
 
        outs.writeByte( this.robot ? 1 : 0); 
 
        outs.writeByte(this.n_printfs); 
 
        for (int a = 0; a < this.n_printfs; a++) {
            __strbuf = new char[this.printfs[a].length()]; this.printfs[a].getChars(0, this.printfs[a].length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
        }
 
    }
 
    public printf_reply_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public printf_reply_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.printf_reply_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.printf_reply_t o = new drc.printf_reply_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.sheriff_id = ins.readInt();
 
        this.robot = ins.readByte()!=0;
 
        this.n_printfs = ins.readByte();
 
        this.printfs = new String[(int) n_printfs];
        for (int a = 0; a < this.n_printfs; a++) {
            __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.printfs[a] = new String(__strbuf);
        }
 
    }
 
    public drc.printf_reply_t copy()
    {
        drc.printf_reply_t outobj = new drc.printf_reply_t();
        outobj.sheriff_id = this.sheriff_id;
 
        outobj.robot = this.robot;
 
        outobj.n_printfs = this.n_printfs;
 
        outobj.printfs = new String[(int) n_printfs];
        if (this.n_printfs > 0)
            System.arraycopy(this.printfs, 0, outobj.printfs, 0, this.n_printfs); 
        return outobj;
    }
 
}

