/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class simple_grasp_t implements lcm.lcm.LCMEncodable
{
    public byte left_state;
    public byte right_state;
 
    public simple_grasp_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x2f8266d85afbb58dL;
 
    public static final byte UNCHANGED = (byte) 0;
    public static final byte CLOSED = (byte) 1;
    public static final byte OPEN = (byte) 2;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.simple_grasp_t.class))
            return 0L;
 
        classes.add(drc.simple_grasp_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.left_state); 
 
        outs.writeByte(this.right_state); 
 
    }
 
    public simple_grasp_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public simple_grasp_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.simple_grasp_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.simple_grasp_t o = new drc.simple_grasp_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.left_state = ins.readByte();
 
        this.right_state = ins.readByte();
 
    }
 
    public drc.simple_grasp_t copy()
    {
        drc.simple_grasp_t outobj = new drc.simple_grasp_t();
        outobj.left_state = this.left_state;
 
        outobj.right_state = this.right_state;
 
        return outobj;
    }
 
}

