/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class transform_stamped_t implements lcm.lcm.LCMEncodable
{
    public String frame_id_;
    public String child_frame_id_;
    public drc.vector_3d_t translation;
    public drc.quaternion_t rotation;
 
    public transform_stamped_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x0b44ed433057bec6L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.transform_stamped_t.class))
            return 0L;
 
        classes.add(drc.transform_stamped_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + drc.vector_3d_t._hashRecursive(classes)
             + drc.quaternion_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        __strbuf = new char[this.frame_id_.length()]; this.frame_id_.getChars(0, this.frame_id_.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        __strbuf = new char[this.child_frame_id_.length()]; this.child_frame_id_.getChars(0, this.child_frame_id_.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        this.translation._encodeRecursive(outs); 
 
        this.rotation._encodeRecursive(outs); 
 
    }
 
    public transform_stamped_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public transform_stamped_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.transform_stamped_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.transform_stamped_t o = new drc.transform_stamped_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.frame_id_ = new String(__strbuf);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.child_frame_id_ = new String(__strbuf);
 
        this.translation = drc.vector_3d_t._decodeRecursiveFactory(ins);
 
        this.rotation = drc.quaternion_t._decodeRecursiveFactory(ins);
 
    }
 
    public drc.transform_stamped_t copy()
    {
        drc.transform_stamped_t outobj = new drc.transform_stamped_t();
        outobj.frame_id_ = this.frame_id_;
 
        outobj.child_frame_id_ = this.child_frame_id_;
 
        outobj.translation = this.translation.copy();
 
        outobj.rotation = this.rotation.copy();
 
        return outobj;
    }
 
}

