/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class twist_t implements lcm.lcm.LCMEncodable
{
    public drc.vector_3d_t linear_velocity;
    public drc.vector_3d_t angular_velocity;
 
    public twist_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x558634eaba4f1769L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.twist_t.class))
            return 0L;
 
        classes.add(drc.twist_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + drc.vector_3d_t._hashRecursive(classes)
             + drc.vector_3d_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.linear_velocity._encodeRecursive(outs); 
 
        this.angular_velocity._encodeRecursive(outs); 
 
    }
 
    public twist_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public twist_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.twist_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.twist_t o = new drc.twist_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.linear_velocity = drc.vector_3d_t._decodeRecursiveFactory(ins);
 
        this.angular_velocity = drc.vector_3d_t._decodeRecursiveFactory(ins);
 
    }
 
    public drc.twist_t copy()
    {
        drc.twist_t outobj = new drc.twist_t();
        outobj.linear_velocity = this.linear_velocity.copy();
 
        outobj.angular_velocity = this.angular_velocity.copy();
 
        return outobj;
    }
 
}

