/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drc;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class utime_two_t implements lcm.lcm.LCMEncodable
{
    public long utime_sim;
    public long utime_wall;
 
    public utime_two_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xcffad7363e11677fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drc.utime_two_t.class))
            return 0L;
 
        classes.add(drc.utime_two_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime_sim); 
 
        outs.writeLong(this.utime_wall); 
 
    }
 
    public utime_two_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public utime_two_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drc.utime_two_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drc.utime_two_t o = new drc.utime_two_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime_sim = ins.readLong();
 
        this.utime_wall = ins.readLong();
 
    }
 
    public drc.utime_two_t copy()
    {
        drc.utime_two_t outobj = new drc.utime_two_t();
        outobj.utime_sim = this.utime_sim;
 
        outobj.utime_wall = this.utime_wall;
 
        return outobj;
    }
 
}

