(cl:defpackage sandia_hand_msgs-msg
  (:use )
  (:export
   "<RAWTACTILE>"
   "RAWTACTILE"
   "<RAWFINGERINERTIAL>"
   "RAWFINGERINERTIAL"
   "<RAWFINGERSTATE>"
   "RAWFINGERSTATE"
   "<RAWMOBOSTATE>"
   "RAWMOBOSTATE"
   "<CALFINGERSTATE>"
   "CALFINGERSTATE"
   "<RAWPALMSTATE>"
   "RAWPALMSTATE"
   "<RELATIVEJOINTCOMMANDS>"
   "RELATIVEJOINTCOMMANDS"
   "<SIMPLEGRASP>"
   "SIMPLEGRASP"
   "<RAWFINGERCOMMANDS>"
   "RAWFINGERCOMMANDS"
   "<PARAMETER>"
   "PARAMETER"
  ))

