(cl:in-package sandia_hand_msgs-msg)
(cl:export '(FMCB_TIME-VAL
          FMCB_TIME
          PP_TIME-VAL
          PP_TIME
          DP_TIME-VAL
          DP_TIME
          PP_TACTILE-VAL
          PP_TACTILE
          DP_TACTILE-VAL
          DP_TACTILE
          PP_STRAIN-VAL
          PP_STRAIN
          MM_ACCEL-VAL
          MM_ACCEL
          PP_ACCEL-VAL
          PP_ACCEL
          DP_ACCEL-VAL
          DP_ACCEL
          MM_MAG-VAL
          MM_MAG
          PP_MAG-VAL
          PP_MAG
          DP_MAG-VAL
          DP_MAG
          PP_TEMP-VAL
          PP_TEMP
          DP_TEMP-VAL
          DP_TEMP
          FMCB_TEMP-VAL
          FMCB_TEMP
          FMCB_VOLTAGE-VAL
          FMCB_VOLTAGE
          FMCB_PB_CURRENT-VAL
          FMCB_PB_CURRENT
          HALL_TGT-VAL
          HALL_TGT
          HALL_POS-VAL
          HALL_POS
          FMCB_EFFORT-VAL
          FMCB_EFFORT
          JOINTS_HALL-VAL
          JOINTS_HALL
          JOINTS_INERTIAL-VAL
          JOINTS_INERTIAL
          JOINTS_INERTIAL_VARIANCE-VAL
          JOINTS_INERTIAL_VARIANCE
))