; Auto-generated. Do not edit!


(cl:in-package sandia_hand_msgs-msg)


;//! \htmlinclude CalFingerState.msg.html

(cl:defclass <CalFingerState> (roslisp-msg-protocol:ros-message)
  ((fmcb_time
    :reader fmcb_time
    :initarg :fmcb_time
    :type cl:float
    :initform 0.0)
   (pp_time
    :reader pp_time
    :initarg :pp_time
    :type cl:float
    :initform 0.0)
   (dp_time
    :reader dp_time
    :initarg :dp_time
    :type cl:float
    :initform 0.0)
   (pp_tactile
    :reader pp_tactile
    :initarg :pp_tactile
    :type (cl:vector cl:float)
   :initform (cl:make-array 6 :element-type 'cl:float :initial-element 0.0))
   (dp_tactile
    :reader dp_tactile
    :initarg :dp_tactile
    :type (cl:vector cl:float)
   :initform (cl:make-array 12 :element-type 'cl:float :initial-element 0.0))
   (pp_strain
    :reader pp_strain
    :initarg :pp_strain
    :type cl:float
    :initform 0.0)
   (mm_accel
    :reader mm_accel
    :initarg :mm_accel
    :type (cl:vector cl:float)
   :initform (cl:make-array 3 :element-type 'cl:float :initial-element 0.0))
   (pp_accel
    :reader pp_accel
    :initarg :pp_accel
    :type (cl:vector cl:float)
   :initform (cl:make-array 3 :element-type 'cl:float :initial-element 0.0))
   (dp_accel
    :reader dp_accel
    :initarg :dp_accel
    :type (cl:vector cl:float)
   :initform (cl:make-array 3 :element-type 'cl:float :initial-element 0.0))
   (mm_mag
    :reader mm_mag
    :initarg :mm_mag
    :type (cl:vector cl:float)
   :initform (cl:make-array 3 :element-type 'cl:float :initial-element 0.0))
   (pp_mag
    :reader pp_mag
    :initarg :pp_mag
    :type (cl:vector cl:float)
   :initform (cl:make-array 3 :element-type 'cl:float :initial-element 0.0))
   (dp_mag
    :reader dp_mag
    :initarg :dp_mag
    :type (cl:vector cl:float)
   :initform (cl:make-array 3 :element-type 'cl:float :initial-element 0.0))
   (pp_temp
    :reader pp_temp
    :initarg :pp_temp
    :type (cl:vector cl:float)
   :initform (cl:make-array 4 :element-type 'cl:float :initial-element 0.0))
   (dp_temp
    :reader dp_temp
    :initarg :dp_temp
    :type (cl:vector cl:float)
   :initform (cl:make-array 4 :element-type 'cl:float :initial-element 0.0))
   (fmcb_temp
    :reader fmcb_temp
    :initarg :fmcb_temp
    :type (cl:vector cl:float)
   :initform (cl:make-array 3 :element-type 'cl:float :initial-element 0.0))
   (fmcb_voltage
    :reader fmcb_voltage
    :initarg :fmcb_voltage
    :type cl:float
    :initform 0.0)
   (fmcb_pb_current
    :reader fmcb_pb_current
    :initarg :fmcb_pb_current
    :type cl:float
    :initform 0.0)
   (hall_tgt
    :reader hall_tgt
    :initarg :hall_tgt
    :type (cl:vector cl:integer)
   :initform (cl:make-array 3 :element-type 'cl:integer :initial-element 0))
   (hall_pos
    :reader hall_pos
    :initarg :hall_pos
    :type (cl:vector cl:integer)
   :initform (cl:make-array 3 :element-type 'cl:integer :initial-element 0))
   (fmcb_effort
    :reader fmcb_effort
    :initarg :fmcb_effort
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 3 :element-type 'cl:fixnum :initial-element 0))
   (joints_hall
    :reader joints_hall
    :initarg :joints_hall
    :type (cl:vector cl:float)
   :initform (cl:make-array 3 :element-type 'cl:float :initial-element 0.0))
   (joints_inertial
    :reader joints_inertial
    :initarg :joints_inertial
    :type (cl:vector cl:float)
   :initform (cl:make-array 3 :element-type 'cl:float :initial-element 0.0))
   (joints_inertial_variance
    :reader joints_inertial_variance
    :initarg :joints_inertial_variance
    :type (cl:vector cl:float)
   :initform (cl:make-array 3 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass CalFingerState (<CalFingerState>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CalFingerState>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CalFingerState)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sandia_hand_msgs-msg:<CalFingerState> is deprecated: use sandia_hand_msgs-msg:CalFingerState instead.")))

(cl:ensure-generic-function 'fmcb_time-val :lambda-list '(m))
(cl:defmethod fmcb_time-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:fmcb_time-val is deprecated.  Use sandia_hand_msgs-msg:fmcb_time instead.")
  (fmcb_time m))

(cl:ensure-generic-function 'pp_time-val :lambda-list '(m))
(cl:defmethod pp_time-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:pp_time-val is deprecated.  Use sandia_hand_msgs-msg:pp_time instead.")
  (pp_time m))

(cl:ensure-generic-function 'dp_time-val :lambda-list '(m))
(cl:defmethod dp_time-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:dp_time-val is deprecated.  Use sandia_hand_msgs-msg:dp_time instead.")
  (dp_time m))

(cl:ensure-generic-function 'pp_tactile-val :lambda-list '(m))
(cl:defmethod pp_tactile-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:pp_tactile-val is deprecated.  Use sandia_hand_msgs-msg:pp_tactile instead.")
  (pp_tactile m))

(cl:ensure-generic-function 'dp_tactile-val :lambda-list '(m))
(cl:defmethod dp_tactile-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:dp_tactile-val is deprecated.  Use sandia_hand_msgs-msg:dp_tactile instead.")
  (dp_tactile m))

(cl:ensure-generic-function 'pp_strain-val :lambda-list '(m))
(cl:defmethod pp_strain-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:pp_strain-val is deprecated.  Use sandia_hand_msgs-msg:pp_strain instead.")
  (pp_strain m))

(cl:ensure-generic-function 'mm_accel-val :lambda-list '(m))
(cl:defmethod mm_accel-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:mm_accel-val is deprecated.  Use sandia_hand_msgs-msg:mm_accel instead.")
  (mm_accel m))

(cl:ensure-generic-function 'pp_accel-val :lambda-list '(m))
(cl:defmethod pp_accel-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:pp_accel-val is deprecated.  Use sandia_hand_msgs-msg:pp_accel instead.")
  (pp_accel m))

(cl:ensure-generic-function 'dp_accel-val :lambda-list '(m))
(cl:defmethod dp_accel-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:dp_accel-val is deprecated.  Use sandia_hand_msgs-msg:dp_accel instead.")
  (dp_accel m))

(cl:ensure-generic-function 'mm_mag-val :lambda-list '(m))
(cl:defmethod mm_mag-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:mm_mag-val is deprecated.  Use sandia_hand_msgs-msg:mm_mag instead.")
  (mm_mag m))

(cl:ensure-generic-function 'pp_mag-val :lambda-list '(m))
(cl:defmethod pp_mag-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:pp_mag-val is deprecated.  Use sandia_hand_msgs-msg:pp_mag instead.")
  (pp_mag m))

(cl:ensure-generic-function 'dp_mag-val :lambda-list '(m))
(cl:defmethod dp_mag-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:dp_mag-val is deprecated.  Use sandia_hand_msgs-msg:dp_mag instead.")
  (dp_mag m))

(cl:ensure-generic-function 'pp_temp-val :lambda-list '(m))
(cl:defmethod pp_temp-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:pp_temp-val is deprecated.  Use sandia_hand_msgs-msg:pp_temp instead.")
  (pp_temp m))

(cl:ensure-generic-function 'dp_temp-val :lambda-list '(m))
(cl:defmethod dp_temp-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:dp_temp-val is deprecated.  Use sandia_hand_msgs-msg:dp_temp instead.")
  (dp_temp m))

(cl:ensure-generic-function 'fmcb_temp-val :lambda-list '(m))
(cl:defmethod fmcb_temp-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:fmcb_temp-val is deprecated.  Use sandia_hand_msgs-msg:fmcb_temp instead.")
  (fmcb_temp m))

(cl:ensure-generic-function 'fmcb_voltage-val :lambda-list '(m))
(cl:defmethod fmcb_voltage-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:fmcb_voltage-val is deprecated.  Use sandia_hand_msgs-msg:fmcb_voltage instead.")
  (fmcb_voltage m))

(cl:ensure-generic-function 'fmcb_pb_current-val :lambda-list '(m))
(cl:defmethod fmcb_pb_current-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:fmcb_pb_current-val is deprecated.  Use sandia_hand_msgs-msg:fmcb_pb_current instead.")
  (fmcb_pb_current m))

(cl:ensure-generic-function 'hall_tgt-val :lambda-list '(m))
(cl:defmethod hall_tgt-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:hall_tgt-val is deprecated.  Use sandia_hand_msgs-msg:hall_tgt instead.")
  (hall_tgt m))

(cl:ensure-generic-function 'hall_pos-val :lambda-list '(m))
(cl:defmethod hall_pos-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:hall_pos-val is deprecated.  Use sandia_hand_msgs-msg:hall_pos instead.")
  (hall_pos m))

(cl:ensure-generic-function 'fmcb_effort-val :lambda-list '(m))
(cl:defmethod fmcb_effort-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:fmcb_effort-val is deprecated.  Use sandia_hand_msgs-msg:fmcb_effort instead.")
  (fmcb_effort m))

(cl:ensure-generic-function 'joints_hall-val :lambda-list '(m))
(cl:defmethod joints_hall-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:joints_hall-val is deprecated.  Use sandia_hand_msgs-msg:joints_hall instead.")
  (joints_hall m))

(cl:ensure-generic-function 'joints_inertial-val :lambda-list '(m))
(cl:defmethod joints_inertial-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:joints_inertial-val is deprecated.  Use sandia_hand_msgs-msg:joints_inertial instead.")
  (joints_inertial m))

(cl:ensure-generic-function 'joints_inertial_variance-val :lambda-list '(m))
(cl:defmethod joints_inertial_variance-val ((m <CalFingerState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sandia_hand_msgs-msg:joints_inertial_variance-val is deprecated.  Use sandia_hand_msgs-msg:joints_inertial_variance instead.")
  (joints_inertial_variance m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CalFingerState>) ostream)
  "Serializes a message object of type '<CalFingerState>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'fmcb_time))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'pp_time))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'dp_time))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'pp_tactile))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'dp_tactile))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'pp_strain))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'mm_accel))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'pp_accel))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'dp_accel))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'mm_mag))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'pp_mag))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'dp_mag))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'pp_temp))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'dp_temp))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'fmcb_temp))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'fmcb_voltage))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'fmcb_pb_current))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'hall_tgt))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'hall_pos))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    ))
   (cl:slot-value msg 'fmcb_effort))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'joints_hall))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'joints_inertial))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'joints_inertial_variance))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CalFingerState>) istream)
  "Deserializes a message object of type '<CalFingerState>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'fmcb_time) (roslisp-utils:decode-double-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'pp_time) (roslisp-utils:decode-double-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'dp_time) (roslisp-utils:decode-double-float-bits bits)))
  (cl:setf (cl:slot-value msg 'pp_tactile) (cl:make-array 6))
  (cl:let ((vals (cl:slot-value msg 'pp_tactile)))
    (cl:dotimes (i 6)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'dp_tactile) (cl:make-array 12))
  (cl:let ((vals (cl:slot-value msg 'dp_tactile)))
    (cl:dotimes (i 12)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits)))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'pp_strain) (roslisp-utils:decode-single-float-bits bits)))
  (cl:setf (cl:slot-value msg 'mm_accel) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'mm_accel)))
    (cl:dotimes (i 3)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'pp_accel) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'pp_accel)))
    (cl:dotimes (i 3)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'dp_accel) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'dp_accel)))
    (cl:dotimes (i 3)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'mm_mag) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'mm_mag)))
    (cl:dotimes (i 3)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'pp_mag) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'pp_mag)))
    (cl:dotimes (i 3)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'dp_mag) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'dp_mag)))
    (cl:dotimes (i 3)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'pp_temp) (cl:make-array 4))
  (cl:let ((vals (cl:slot-value msg 'pp_temp)))
    (cl:dotimes (i 4)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'dp_temp) (cl:make-array 4))
  (cl:let ((vals (cl:slot-value msg 'dp_temp)))
    (cl:dotimes (i 4)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'fmcb_temp) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'fmcb_temp)))
    (cl:dotimes (i 3)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits)))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'fmcb_voltage) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'fmcb_pb_current) (roslisp-utils:decode-single-float-bits bits)))
  (cl:setf (cl:slot-value msg 'hall_tgt) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'hall_tgt)))
    (cl:dotimes (i 3)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))))
  (cl:setf (cl:slot-value msg 'hall_pos) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'hall_pos)))
    (cl:dotimes (i 3)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))))
  (cl:setf (cl:slot-value msg 'fmcb_effort) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'fmcb_effort)))
    (cl:dotimes (i 3)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))))
  (cl:setf (cl:slot-value msg 'joints_hall) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'joints_hall)))
    (cl:dotimes (i 3)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'joints_inertial) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'joints_inertial)))
    (cl:dotimes (i 3)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'joints_inertial_variance) (cl:make-array 3))
  (cl:let ((vals (cl:slot-value msg 'joints_inertial_variance)))
    (cl:dotimes (i 3)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CalFingerState>)))
  "Returns string type for a message object of type '<CalFingerState>"
  "sandia_hand_msgs/CalFingerState")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CalFingerState)))
  "Returns string type for a message object of type 'CalFingerState"
  "sandia_hand_msgs/CalFingerState")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CalFingerState>)))
  "Returns md5sum for a message object of type '<CalFingerState>"
  "e6c255966d7401429661c8a57b905e54")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CalFingerState)))
  "Returns md5sum for a message object of type 'CalFingerState"
  "e6c255966d7401429661c8a57b905e54")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CalFingerState>)))
  "Returns full string definition for message of type '<CalFingerState>"
  (cl:format cl:nil "float64 fmcb_time~%float64 pp_time~%float64 dp_time~%float32[6]  pp_tactile~%float32[12] dp_tactile~%float32 pp_strain~%float32[3] mm_accel~%float32[3] pp_accel~%float32[3] dp_accel~%float32[3] mm_mag~%float32[3] pp_mag~%float32[3] dp_mag~%float32[4] pp_temp~%float32[4] dp_temp~%float32[3] fmcb_temp~%float32 fmcb_voltage~%float32 fmcb_pb_current~%int32[3] hall_tgt~%int32[3] hall_pos~%int16[3] fmcb_effort~%float32[3] joints_hall~%float32[3] joints_inertial~%float32[3] joints_inertial_variance~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CalFingerState)))
  "Returns full string definition for message of type 'CalFingerState"
  (cl:format cl:nil "float64 fmcb_time~%float64 pp_time~%float64 dp_time~%float32[6]  pp_tactile~%float32[12] dp_tactile~%float32 pp_strain~%float32[3] mm_accel~%float32[3] pp_accel~%float32[3] dp_accel~%float32[3] mm_mag~%float32[3] pp_mag~%float32[3] dp_mag~%float32[4] pp_temp~%float32[4] dp_temp~%float32[3] fmcb_temp~%float32 fmcb_voltage~%float32 fmcb_pb_current~%int32[3] hall_tgt~%int32[3] hall_pos~%int16[3] fmcb_effort~%float32[3] joints_hall~%float32[3] joints_inertial~%float32[3] joints_inertial_variance~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CalFingerState>))
  (cl:+ 0
     8
     8
     8
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'pp_tactile) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'dp_tactile) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'mm_accel) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'pp_accel) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'dp_accel) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'mm_mag) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'pp_mag) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'dp_mag) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'pp_temp) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'dp_temp) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'fmcb_temp) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4
     4
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'hall_tgt) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'hall_pos) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'fmcb_effort) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 2)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'joints_hall) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'joints_inertial) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'joints_inertial_variance) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CalFingerState>))
  "Converts a ROS message object to a list"
  (cl:list 'CalFingerState
    (cl:cons ':fmcb_time (fmcb_time msg))
    (cl:cons ':pp_time (pp_time msg))
    (cl:cons ':dp_time (dp_time msg))
    (cl:cons ':pp_tactile (pp_tactile msg))
    (cl:cons ':dp_tactile (dp_tactile msg))
    (cl:cons ':pp_strain (pp_strain msg))
    (cl:cons ':mm_accel (mm_accel msg))
    (cl:cons ':pp_accel (pp_accel msg))
    (cl:cons ':dp_accel (dp_accel msg))
    (cl:cons ':mm_mag (mm_mag msg))
    (cl:cons ':pp_mag (pp_mag msg))
    (cl:cons ':dp_mag (dp_mag msg))
    (cl:cons ':pp_temp (pp_temp msg))
    (cl:cons ':dp_temp (dp_temp msg))
    (cl:cons ':fmcb_temp (fmcb_temp msg))
    (cl:cons ':fmcb_voltage (fmcb_voltage msg))
    (cl:cons ':fmcb_pb_current (fmcb_pb_current msg))
    (cl:cons ':hall_tgt (hall_tgt msg))
    (cl:cons ':hall_pos (hall_pos msg))
    (cl:cons ':fmcb_effort (fmcb_effort msg))
    (cl:cons ':joints_hall (joints_hall msg))
    (cl:cons ':joints_inertial (joints_inertial msg))
    (cl:cons ':joints_inertial_variance (joints_inertial_variance msg))
))
