/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _isam_slam_position_t_h
#define _isam_slam_position_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _isam_slam_position_t isam_slam_position_t;
struct _isam_slam_position_t
{
    int64_t    utime;
    double     pos[3];
    double     orientation[4];
};

isam_slam_position_t   *isam_slam_position_t_copy(const isam_slam_position_t *p);
void isam_slam_position_t_destroy(isam_slam_position_t *p);

typedef struct _isam_slam_position_t_subscription_t isam_slam_position_t_subscription_t;
typedef void(*isam_slam_position_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const isam_slam_position_t *msg, void *user);

int isam_slam_position_t_publish(lcm_t *lcm, const char *channel, const isam_slam_position_t *p);
isam_slam_position_t_subscription_t* isam_slam_position_t_subscribe(lcm_t *lcm, const char *channel, isam_slam_position_t_handler_t f, void *userdata);
int isam_slam_position_t_unsubscribe(lcm_t *lcm, isam_slam_position_t_subscription_t* hid);
int isam_slam_position_t_subscription_set_queue_capacity(isam_slam_position_t_subscription_t* subs,
                              int num_messages);


int  isam_slam_position_t_encode(void *buf, int offset, int maxlen, const isam_slam_position_t *p);
int  isam_slam_position_t_decode(const void *buf, int offset, int maxlen, isam_slam_position_t *p);
int  isam_slam_position_t_decode_cleanup(isam_slam_position_t *p);
int  isam_slam_position_t_encoded_size(const isam_slam_position_t *p);

// LCM support functions. Users should not call these
int64_t __isam_slam_position_t_get_hash(void);
int64_t __isam_slam_position_t_hash_recursive(const __lcm_hash_ptr *p);
int     __isam_slam_position_t_encode_array(void *buf, int offset, int maxlen, const isam_slam_position_t *p, int elements);
int     __isam_slam_position_t_decode_array(const void *buf, int offset, int maxlen, isam_slam_position_t *p, int elements);
int     __isam_slam_position_t_decode_array_cleanup(isam_slam_position_t *p, int elements);
int     __isam_slam_position_t_encoded_array_size(const isam_slam_position_t *p, int elements);
int     __isam_slam_position_t_clone_array(const isam_slam_position_t *p, isam_slam_position_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
