/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __mav_filter_state_t_hpp__
#define __mav_filter_state_t_hpp__

#include <vector>

namespace mav
{

class filter_state_t
{
    public:
        int64_t    utime;
        double     quat[4];
        int32_t    num_states;
        std::vector< double > state;
        int32_t    num_cov_elements;
        std::vector< double > cov;

    public:
        inline int encode(void *buf, int offset, int maxlen) const;
        inline int getEncodedSize() const;
        inline int decode(const void *buf, int offset, int maxlen);
        inline static int64_t getHash();
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int filter_state_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int filter_state_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int filter_state_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t filter_state_t::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* filter_state_t::getTypeName()
{
    return "filter_state_t";
}

int filter_state_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->utime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->quat[0], 4);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_states, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->state[0], this->num_states);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_cov_elements, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->cov[0], this->num_cov_elements);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int filter_state_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->utime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->quat[0], 4);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_states, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->state.resize(this->num_states);
    if(this->num_states) {
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->state[0], this->num_states);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_cov_elements, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->cov.resize(this->num_cov_elements);
    if(this->num_cov_elements) {
        tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->cov[0], this->num_cov_elements);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int filter_state_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 4);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, this->num_states);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, this->num_cov_elements);
    return enc_size;
}

int64_t filter_state_t::_computeHash(const __lcm_hash_ptr *)
{
    int64_t hash = 0x0a8b94bf1e099115LL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
