(cl:defpackage multisense_ros-msg
  (:use )
  (:export
   "<RAWCAMDATA>"
   "RAWCAMDATA"
   "<SENSORSTATUS>"
   "SENSORSTATUS"
   "<RAWLIDARDATA>"
   "RAWLIDARDATA"
   "<SENSORDIAGNOSTICS>"
   "SENSORDIAGNOSTICS"
   "<RAWCAMCONFIG>"
   "RAWCAMCONFIG"
   "<JOINTDIAGNOSTICS>"
   "JOINTDIAGNOSTICS"
  ))

