(cl:in-package multisense_ros-msg)
(cl:export '(WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          FRAMES_PER_SECOND-VAL
          FRAMES_PER_SECOND
          GAIN-VAL
          GAIN
          EXPOSURE_TIME-VAL
          EXPOSURE_TIME
          FX-VAL
          FX
          FY-VAL
          FY
          CX-VAL
          CX
          CY-VAL
          CY
          TX-VAL
          TX
          TY-VAL
          TY
          TZ-VAL
          TZ
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
))