mex -I$DRC_BASE/software/build/include/ ...
    -I/usr/include/glib-2.0/ ...
    -I/usr/lib/x86_64-linux-gnu/glib-2.0/include/ ...
    -L/home/drc/drc/software/build/lib ...
    -lbot2-core -lbot2-frames -lbot2-param-client bot_frames_transform_vec_mex.cpp
