function data = import_irobot_hand_data(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   JOINTANGLEESTIMATIONDATA = IMPORTFILE(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   JOINTANGLEESTIMATIONDATA = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   jointangleestimationdata =
%   importfile('joint_angle_estimation_data.csv', 2, 496);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2013/11/15 09:46:07

%% Initialize variables.
delimiter = ',';
if nargin<=2
  startRow = 2;
  endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
  frewind(fileID);
  dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
  for col=1:length(dataArray)
    dataArray{col} = [dataArray{col};dataArrayBlock{col}];
  end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
data = dataset(dataArray{1:end-1}, 'VarNames', {'time','motorHallEncoder0','motorHallEncoder1','motorHallEncoder2','proximalJointAngle0','proximalJointAngle1','proximalJointAngle2'});
