/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __mav_map_measurement_function_t_hpp__
#define __mav_map_measurement_function_t_hpp__

#include <vector>
#include "lcmtypes/occ_map/pixel_map_t.hpp"
#include "lcmtypes/occ_map/pixel_map_t.hpp"
#include "lcmtypes/occ_map/pixel_map_t.hpp"
#include "lcmtypes/occ_map/pixel_map_t.hpp"
#include "lcmtypes/occ_map/pixel_map_t.hpp"
#include "lcmtypes/occ_map/pixel_map_t.hpp"

namespace mav
{

class map_measurement_function_t
{
    public:
        int64_t    utime;
        double     z_height;
        double     theta;
        occ_map::pixel_map_t phi_psi_xy_cov_map;
        occ_map::pixel_map_t phi_psi_xy_information_map;
        occ_map::pixel_map_t xy_max_information;
        occ_map::pixel_map_t xy_min_information;
        int32_t    num_xy_maps;
        std::vector< occ_map::pixel_map_t > xy_information_maps;
        std::vector< occ_map::pixel_map_t > xy_cov_maps;

    public:
        inline int encode(void *buf, int offset, int maxlen) const;
        inline int getEncodedSize() const;
        inline int decode(const void *buf, int offset, int maxlen);
        inline static int64_t getHash();
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int map_measurement_function_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int map_measurement_function_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int map_measurement_function_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t map_measurement_function_t::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* map_measurement_function_t::getTypeName()
{
    return "map_measurement_function_t";
}

int map_measurement_function_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->utime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->z_height, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->theta, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->phi_psi_xy_cov_map._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->phi_psi_xy_information_map._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->xy_max_information._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->xy_min_information._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_xy_maps, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_xy_maps; a0++) {
        tlen = this->xy_information_maps[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->num_xy_maps; a0++) {
        tlen = this->xy_cov_maps[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int map_measurement_function_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->utime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->z_height, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->theta, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->phi_psi_xy_cov_map._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->phi_psi_xy_information_map._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->xy_max_information._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->xy_min_information._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_xy_maps, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->xy_information_maps.resize(this->num_xy_maps);
    for (int a0 = 0; a0 < this->num_xy_maps; a0++) {
        tlen = this->xy_information_maps[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    this->xy_cov_maps.resize(this->num_xy_maps);
    for (int a0 = 0; a0 < this->num_xy_maps; a0++) {
        tlen = this->xy_cov_maps[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int map_measurement_function_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += this->phi_psi_xy_cov_map._getEncodedSizeNoHash();
    enc_size += this->phi_psi_xy_information_map._getEncodedSizeNoHash();
    enc_size += this->xy_max_information._getEncodedSizeNoHash();
    enc_size += this->xy_min_information._getEncodedSizeNoHash();
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_xy_maps; a0++) {
        enc_size += this->xy_information_maps[a0]._getEncodedSizeNoHash();
    }
    for (int a0 = 0; a0 < this->num_xy_maps; a0++) {
        enc_size += this->xy_cov_maps[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

int64_t map_measurement_function_t::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == map_measurement_function_t::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, (void*)map_measurement_function_t::getHash };

    int64_t hash = 0x33fba992c58d7ed0LL +
         occ_map::pixel_map_t::_computeHash(&cp) +
         occ_map::pixel_map_t::_computeHash(&cp) +
         occ_map::pixel_map_t::_computeHash(&cp) +
         occ_map::pixel_map_t::_computeHash(&cp) +
         occ_map::pixel_map_t::_computeHash(&cp) +
         occ_map::pixel_map_t::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
