function pose = decodePosition3d(position_3d)
  pose = zeros(6,1);
  pose(1:3) = [position_3d.translation.x; position_3d.translation.y; position_3d.translation.z];
  pose(4:6) = quat2rpy([position_3d.rotation.w,...
                                      position_3d.rotation.x,...
                                      position_3d.rotation.y,...
                                      position_3d.rotation.z]);
end
