/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _sm_rigid_transform_2d_t_h
#define _sm_rigid_transform_2d_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _sm_rigid_transform_2d_t sm_rigid_transform_2d_t;
struct _sm_rigid_transform_2d_t
{
    int64_t    utime;
    int64_t    utime_prev;
    double     pos[2];
    double     theta;
    double     cov[9];
};

sm_rigid_transform_2d_t   *sm_rigid_transform_2d_t_copy(const sm_rigid_transform_2d_t *p);
void sm_rigid_transform_2d_t_destroy(sm_rigid_transform_2d_t *p);

typedef struct _sm_rigid_transform_2d_t_subscription_t sm_rigid_transform_2d_t_subscription_t;
typedef void(*sm_rigid_transform_2d_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const sm_rigid_transform_2d_t *msg, void *user);

int sm_rigid_transform_2d_t_publish(lcm_t *lcm, const char *channel, const sm_rigid_transform_2d_t *p);
sm_rigid_transform_2d_t_subscription_t* sm_rigid_transform_2d_t_subscribe(lcm_t *lcm, const char *channel, sm_rigid_transform_2d_t_handler_t f, void *userdata);
int sm_rigid_transform_2d_t_unsubscribe(lcm_t *lcm, sm_rigid_transform_2d_t_subscription_t* hid);
int sm_rigid_transform_2d_t_subscription_set_queue_capacity(sm_rigid_transform_2d_t_subscription_t* subs,
                              int num_messages);


int  sm_rigid_transform_2d_t_encode(void *buf, int offset, int maxlen, const sm_rigid_transform_2d_t *p);
int  sm_rigid_transform_2d_t_decode(const void *buf, int offset, int maxlen, sm_rigid_transform_2d_t *p);
int  sm_rigid_transform_2d_t_decode_cleanup(sm_rigid_transform_2d_t *p);
int  sm_rigid_transform_2d_t_encoded_size(const sm_rigid_transform_2d_t *p);

// LCM support functions. Users should not call these
int64_t __sm_rigid_transform_2d_t_get_hash(void);
int64_t __sm_rigid_transform_2d_t_hash_recursive(const __lcm_hash_ptr *p);
int     __sm_rigid_transform_2d_t_encode_array(void *buf, int offset, int maxlen, const sm_rigid_transform_2d_t *p, int elements);
int     __sm_rigid_transform_2d_t_decode_array(const void *buf, int offset, int maxlen, sm_rigid_transform_2d_t *p, int elements);
int     __sm_rigid_transform_2d_t_decode_array_cleanup(sm_rigid_transform_2d_t *p, int elements);
int     __sm_rigid_transform_2d_t_encoded_array_size(const sm_rigid_transform_2d_t *p, int elements);
int     __sm_rigid_transform_2d_t_clone_array(const sm_rigid_transform_2d_t *p, sm_rigid_transform_2d_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
