/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "lcmtypes/mav_filter_state_t.h"

static int __mav_filter_state_t_hash_computed;
static int64_t __mav_filter_state_t_hash;

int64_t __mav_filter_state_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __mav_filter_state_t_get_hash)
            return 0;

    const __lcm_hash_ptr cp = { p, (void*)__mav_filter_state_t_get_hash };
    (void) cp;

    int64_t hash = 0x0a8b94bf1e099115LL
         + __int64_t_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __mav_filter_state_t_get_hash(void)
{
    if (!__mav_filter_state_t_hash_computed) {
        __mav_filter_state_t_hash = __mav_filter_state_t_hash_recursive(NULL);
        __mav_filter_state_t_hash_computed = 1;
    }

    return __mav_filter_state_t_hash;
}

int __mav_filter_state_t_encode_array(void *buf, int offset, int maxlen, const mav_filter_state_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].quat, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_states), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].state, p[element].num_states);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_cov_elements), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].cov, p[element].num_cov_elements);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int mav_filter_state_t_encode(void *buf, int offset, int maxlen, const mav_filter_state_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __mav_filter_state_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __mav_filter_state_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __mav_filter_state_t_encoded_array_size(const mav_filter_state_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].utime), 1);

        size += __double_encoded_array_size(p[element].quat, 4);

        size += __int32_t_encoded_array_size(&(p[element].num_states), 1);

        size += __double_encoded_array_size(p[element].state, p[element].num_states);

        size += __int32_t_encoded_array_size(&(p[element].num_cov_elements), 1);

        size += __double_encoded_array_size(p[element].cov, p[element].num_cov_elements);

    }
    return size;
}

int mav_filter_state_t_encoded_size(const mav_filter_state_t *p)
{
    return 8 + __mav_filter_state_t_encoded_array_size(p, 1);
}

int __mav_filter_state_t_decode_array(const void *buf, int offset, int maxlen, mav_filter_state_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].quat, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_states), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].state = (double*) lcm_malloc(sizeof(double) * p[element].num_states);
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].state, p[element].num_states);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_cov_elements), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].cov = (double*) lcm_malloc(sizeof(double) * p[element].num_cov_elements);
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].cov, p[element].num_cov_elements);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __mav_filter_state_t_decode_array_cleanup(mav_filter_state_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].utime), 1);

        __double_decode_array_cleanup(p[element].quat, 4);

        __int32_t_decode_array_cleanup(&(p[element].num_states), 1);

        __double_decode_array_cleanup(p[element].state, p[element].num_states);
        if (p[element].state) free(p[element].state);

        __int32_t_decode_array_cleanup(&(p[element].num_cov_elements), 1);

        __double_decode_array_cleanup(p[element].cov, p[element].num_cov_elements);
        if (p[element].cov) free(p[element].cov);

    }
    return 0;
}

int mav_filter_state_t_decode(const void *buf, int offset, int maxlen, mav_filter_state_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __mav_filter_state_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __mav_filter_state_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int mav_filter_state_t_decode_cleanup(mav_filter_state_t *p)
{
    return __mav_filter_state_t_decode_array_cleanup(p, 1);
}

int __mav_filter_state_t_clone_array(const mav_filter_state_t *p, mav_filter_state_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);

        __double_clone_array(p[element].quat, q[element].quat, 4);

        __int32_t_clone_array(&(p[element].num_states), &(q[element].num_states), 1);

        q[element].state = (double*) lcm_malloc(sizeof(double) * q[element].num_states);
        __double_clone_array(p[element].state, q[element].state, p[element].num_states);

        __int32_t_clone_array(&(p[element].num_cov_elements), &(q[element].num_cov_elements), 1);

        q[element].cov = (double*) lcm_malloc(sizeof(double) * q[element].num_cov_elements);
        __double_clone_array(p[element].cov, q[element].cov, p[element].num_cov_elements);

    }
    return 0;
}

mav_filter_state_t *mav_filter_state_t_copy(const mav_filter_state_t *p)
{
    mav_filter_state_t *q = (mav_filter_state_t*) malloc(sizeof(mav_filter_state_t));
    __mav_filter_state_t_clone_array(p, q, 1);
    return q;
}

void mav_filter_state_t_destroy(mav_filter_state_t *p)
{
    __mav_filter_state_t_decode_array_cleanup(p, 1);
    free(p);
}

int mav_filter_state_t_publish(lcm_t *lc, const char *channel, const mav_filter_state_t *p)
{
      int max_data_size = mav_filter_state_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = mav_filter_state_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _mav_filter_state_t_subscription_t {
    mav_filter_state_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void mav_filter_state_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    mav_filter_state_t p;
    memset(&p, 0, sizeof(mav_filter_state_t));
    status = mav_filter_state_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding mav_filter_state_t!!!\n", status);
        return;
    }

    mav_filter_state_t_subscription_t *h = (mav_filter_state_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    mav_filter_state_t_decode_cleanup (&p);
}

mav_filter_state_t_subscription_t* mav_filter_state_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    mav_filter_state_t_handler_t f, void *userdata)
{
    mav_filter_state_t_subscription_t *n = (mav_filter_state_t_subscription_t*)
                       malloc(sizeof(mav_filter_state_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 mav_filter_state_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg mav_filter_state_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int mav_filter_state_t_subscription_set_queue_capacity (mav_filter_state_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int mav_filter_state_t_unsubscribe(lcm_t *lcm, mav_filter_state_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe mav_filter_state_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

