function param_sets = getDefaults(r, sim_mode)
typecheck(r, 'DRCAtlas');
if sim_mode
  param_sets = struct('standing', drcAtlasParams.StandingSim(r),...
                      'walking', drcAtlasParams.WalkingSim(r),...
                      'manip', drcAtlasParams.ManipSim(r),...
                      'recovery', drcAtlasParams.RecoverySim(r),...
                      'bracing', drcAtlasParams.BracingSim(r));
else
  param_sets = struct('standing', drcAtlasParams.StandingHardware(r),...
                      'walking', drcAtlasParams.WalkingHardware(r),...
                      'manip', drcAtlasParams.ManipHardware(r),...
                      'recovery', drcAtlasParams.RecoveryHardware(r),...
                      'bracing', drcAtlasParams.BracingHardware(r));
end
  