function param_sets = getDefaults(r)
typecheck(r, 'DRCAtlas');
param_sets = struct('standing_hardware', drcAtlasParams.StandingHardware(r),...
                    'standing_sim', drcAtlasParams.StandingSim(r),...
                    'walking_hardware', drcAtlasParams.WalkingHardware(r),...
                    'walking_sim', drcAtlasParams.WalkingSim(r),...
                    'manip_hardware', drcAtlasParams.ManipHardware(r),...
                    'manip_sim', drcAtlasParams.ManipSim(r));

if r.atlas_version == 5
  param_sets.bracing_sim = drcAtlasParams.BracingSim(r);
  param_sets.bracing_hardware = drcAtlasParams.BracingHardware(r);
else
  warning('Drake:BracingNotAvailable', 'Bracing params only defined for Atlas v5. Bracing behavior will not work with this robot.');
end
  